### ISSUE TITLE
Actions fail (404) in long-running tab without strong indication of failure in the UI

### ISSUE THREAD

**Issue by mbolohan** [richpri/board18v2#6]
Steps to reproduce what I'm seeing, using Chrome:
1) Navigate to https://prod1.board18.org/board18Map.php?dogame=<id> to play a game, take a turn
2) Leave tab open for a few hours
3) Come back to the tab to take my next turn
4) Observe a 404 in console
5) Taking actions in the game have no effect, more 404s in the logs
6) No strong UI indication that the actions are failing, but observe that the "Your action has been successfully updated in the database" text is not displayed.
7) Someone has to tell me that my actions did not take effect

Refreshing the page fixes the problem. My group is seeing this frequently across all players. I think this is a regression in the last 1-2 weeks.

See attached console log. Let me know if I can provide more info.

Adding a more prominent error message in the UI to prompt a refresh would be fine, but ideally we can get this back to how things were a few weeks ago where long-running tabs did not hit 404s.

[prod1.board18.org-1600129071095.log](https://github.com/richpri/board18v2/files/5221740/prod1.board18.org-1600129071095.log)

**Comment by richpri** [comment]
@mbolohan 
The board18 project does not use github to track issues.
BOARD18 has a bugzilla site at https://bugs.board18.org/
I have used your above error report to create Bug 196 on this site.
I will start to investigate the issue tomorrow.

If you wish to track progress on this issue, please obtain a user ID on this site.
This WIKI page may be of help with that - https://wiki.board18.org/w/How_to_Report_a_Problem
You can reach me directly at rich02@board18.org 
If you send me the email address that is your user ID for the Bugzilla then I will add you to the CC list for this issue.
